### ISSUE TITLE
工作区显示异常

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-window-switch#10]
版本：20.04LTS
iso：ubuntukylin-ukui3.0-20200313-amd64.iso
测试环境：联想启天M415-N000台式机
测试步骤：
1.任务栏打开工作区
2.按esc键退出

预期结果： 工区界面显示正常
实际结果：.鼠标点击任务栏工作区-按esc退出，再次打开工作区，发现右边显示桌面位置向下移动了

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
