### ISSUE TITLE
【双屏模式】工作区显示在扩展屏

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-window-switch#11]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、桌面打开多个窗口
2、将其中一个窗口拖至扩展屏
3、点击工作区按钮

预期结果：工作区显示在主屏

实际结果：工作区显示在扩展屏

**Comment by droiing** [comment]
已确认，多屏下坐标出现异常。

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
