### ISSUE TITLE
【双屏模式】工作区显示异常

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-window-switch#12]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、将窗口1拖至扩展屏，查看工作区
2、将窗口1拖回主屏，查看工作区

预期结果：
1、工作区显示在主屏
2、工作区显示在主屏，并显示正常

实际结果：
1、工作区显示在扩展屏
2、工作区显示在主屏和扩展屏上，且显示异常

**Comment by liumin0322** [comment]
![2020-03-20 20-36-42屏幕截图](https://user-images.githubusercontent.com/48200161/77164171-a9177600-6aea-11ea-93c7-6845559b0e49.png)

**Comment by droiing** [comment]
问题同#11

**Comment by liumin0322** [comment]
Tested pass in the 20200410 version
