### ISSUE TITLE
The multi-window function background is not following the desktop background correctly

### ISSUE THREAD

**Issue by ikeyhzj** [ukui/ukui-window-switch#14]
Version: 20.04LTS
iso: ubuntukylin-20.04-050803-amd64
Test environment: ThinkPad T480 desktop

Test steps:
Setting - personalization - background: set the background as a picture, click the multi-window function of the task bar, the background is normal; Set the background to the color, click the multi-window function of the task bar, the background is not correct; Set the background as a picture again. Click the multi-window function in the task bar. The background is not correct

Expected result: Multi-window backgrounds follow background changes correctly
Actual result: not correct

**Comment by liumin0322** [comment]
20200717 test passed
