### ISSUE TITLE
默认仅1个工作区

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-window-switch#6]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、点击任务栏工作区图标

预期结果：多工作区模式默认显示4个

实际结果：仅1个工作区

**Comment by xiaodongliu-nudt** [comment]
关键是没有增加工作区的按钮了Version：20200327

**Comment by droiing** [comment]
增减工作区功能在20.10里面完成，当前ukwm默认四个工作区，ukui-kwin还是默认1个，需要ukui-kwin更新默认设置。
