### ISSUE TITLE
应用最小化时，缩略图为空

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-window-switch#7]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开控制面板和浏览器，并最小化
2、查看工作区模式

预期结果：可正常显示当前应用

实际结果：控制面板和浏览器的缩略图为空

**Comment by droiing** [comment]
ukwm环境下不存在该问题，ukui-kwin环境下，需要更改ukui-kwin的默认配置
