### ISSUE TITLE
终端的缩略图显示不完全

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-window-switch#8]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、打开终端
2、切换至工作区模式

预期结果：正常

实际结果：终端缩略图显示为竖向长方形，且截取不完整

**Comment by droiing** [comment]
kwin的Frame区域和原始ukwm计算法方式不一样，需要做区分。
当前禁用Frame窗口修复来规避问题，未关联改issue和commit:d108e2036468fe171b9ba5d1ae55556c12d3657b。

待最终解决所有问题后关闭。
