### ISSUE TITLE
属性窗口显示异常

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-window-switch#9]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-20200314-amd64.iso
测试环境：联想笔记本-X240

测试步骤：
1、桌面上，分别打开3个文件的右键属性
2、切至多工作区模式

预期结果：显示正常

实际结果：属性的窗口大小和内容均显示异常

**Comment by droiing** [comment]
与#8 是同一个问题
